In [2]:
import pandas as pd
import numpy as np
from collections import Counter
import matplotlib.pyplot as plt

trips=np.array(pd.read_csv(r"/home/aziza/Downloads/coding/friendly-funicular/trips.csv",encoding='cp866'))
print(trips)

[[  1.    2.    4.   49.    8.1]
 [  1.    3.    3.   35.    6.8]
 [  1.    4.    2.   75.    9.3]
 ...
 [ 22.    1.    1.  140.   84.8]
 [ 22.    2.    3.  120.   72.6]
 [ 22.   22.   18.   25.    1.5]]


In [3]:
T=np.zeros([22,22])
O=np.zeros([22])
D=np.zeros([22])
z=0
for i in range(22):
    O[i]=Counter(trips.T[0])[i+1]
    D[i]=Counter(trips.T[1])[i+1]
    tr=np.zeros([22])
    print(z,int(O[i])+z-1)
    for j in range(z,int(O[i])+z):
        tr[int(trips[j][1])-1]=trips[j][2]
        if j==int(O[i])+z-1:
            z=int(O[i])+z
    print(tr)
    T[i]=tr
print(T)

0 8
[0. 4. 3. 2. 2. 4. 6. 3. 0. 0. 1. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
9 19
[29. 51.  5.  5.  5.  5.  1.  8.  6.  0.  0.  1.  0.  0.  6.  0.  0.  0.
  0.  0.  0.  0.]
20 32
[28. 11. 55.  8.  3.  5.  3.  4.  2.  0.  3.  1.  0.  1.  2.  0.  0.  0.
  0.  0.  0.  0.]
33 43
[31.  6.  4. 36.  5.  3.  4.  4.  2.  0.  0.  2.  1.  0.  0.  0.  0.  0.
  0.  0.  0.  0.]
44 55
[27.  6.  4.  7. 38. 12.  3.  6.  4.  0.  1.  4.  0.  0.  0.  0.  0.  0.
  1.  0.  0.  0.]
56 68
[22. 11.  3.  3. 11. 42.  9.  8.  0.  0.  0.  1.  2.  1.  2.  0.  0.  1.
  0.  0.  0.  0.]
69 82
[32.  5.  1.  5.  5.  7. 53.  8.  3.  0.  0.  0.  3.  2.  2.  1.  0.  1.
  0.  0.  0.  0.]
83 94
[30.  6.  2.  5.  3.  8.  6. 50.  4.  0.  0.  1.  2.  1.  0.  0.  0.  0.
  0.  0.  0.  0.]
95 106
[22.  8.  2.  1.  3.  3.  2.  9. 28.  1.  0.  1.  0.  0.  3.  0.  0.  0.
  0.  0.  0.  0.]
107 109
[0. 1. 0. 0. 0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
110 120
[18.  0. 15. 11.  1.  2.  0.  4.  0.  0. 67.  2.  1.  1.  2.  0.  0.

In [4]:
N=6
A=np.zeros([N,22])
B=np.zeros([N,22])
for i in range(22):
    A[0][i]=1
    B[0][i]=1

In [5]:
c=np.zeros([22,22])
z=0
for i in range(22):
    tr=np.zeros([22])
    print(z,int(O[i])+z-1)
    for j in range(z,int(O[i])+z):
        tr[int(trips[j][1])-1]=trips[j][3]
        if j==int(O[i])+z-1:
            z=int(O[i])+z
    print(tr)
    c[i]=tr
print(c)

0 8
[ 0. 49. 35. 75. 30. 52. 48. 48.  0.  0. 30.  0. 50.  0.  0.  0.  0.  0.
  0.  0.  0.  0.]
9 19
[53. 27. 51. 55. 58. 65. 30. 71. 72.  0.  0. 60.  0.  0. 48.  0.  0.  0.
  0.  0.  0.  0.]
20 32
[ 53.  67.  34.  57.  67.  86.  85.  85.  90.   0.  52.  90.   0. 165.
  98.   0.   0.   0.   0.   0.   0.   0.]
33 43
[ 55.  77.  36.  37.  52.  35.  70.  79. 112.   0.   0.  90.  90.   0.
   0.   0.   0.   0.   0.   0.   0.   0.]
44 55
[ 60.  82.  70.  48.  31.  60.  58.  83.  59.   0.  90.  41.   0.   0.
   0.   0.   0.   0. 240.   0.   0.   0.]
56 68
[ 66.  66.  80.  70.  59.  37.  48.  69.   0.   0.   0.  40.  45. 120.
 105.   0.   0.  75.   0.   0.   0.   0.]
69 82
[ 54.  89. 120.  63.  78.  58.  29.  44.  67.   0.   0.   0.  38. 135.
 125.  80.   0. 100.   0.   0.   0.   0.]
83 94
[53. 58. 60. 60. 75. 56. 44. 30. 68.  0.  0. 90. 28. 90.  0.  0.  0.  0.
  0.  0.  0.  0.]
95 106
[ 62.  59.  85. 105.  68.  73.  68.  44.  28.  90.   0. 120.   0.   0.
 140.   0.   0.   0.   0.   0.   0.   0

In [6]:
F=np.zeros([22,22])
FF=np.zeros([N,22,22])
for i in range(22):
    for j in range(22):
        F[i][j]=T[i][j]/(A[0][i]*O[i]*D[j]*B[0][j])
        FF[0]=F

In [7]:
#print(A)
for k in range(1):
    for i in range(22):
        if k%2==0:
            B[k+1]=B[k]
            A[k+1][i]=(np.sum(B[k]*O/FF[k][i]))**(-1)
            print((k,(FF[k][21])))
        else:
            A[k+1]=A[k]
            B[k+1][i]=(np.sum(A[k]*D/FF[k].T[i]))**(-1)
            #print((k,FF[k].T[i]))
    for j in range(22):
        F[i][j]=T[i][j]/(A[k+1][i]*O[i]*D[j]*B[k+1][j])
    FF[k]=F
    #print(F)
#print(A)

(0, array([0.01851852, 0.05882353, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 3.        ]))
(0, array([0.01851852, 0.05882353, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 3.        ]))
(0, array([0.01851852, 0.05882353, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 3.        ]))
(0, array([0.01851852, 0.05882353, 0.        , 0.        , 0.        ,
       0.     

/home/aziza/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  
/home/aziza/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: RuntimeWarning: divide by zero encountered in double_scalars
  del sys.path[0]
/home/aziza/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in double_scalars
  del sys.path[0]
